---
#- hosts: all
#  sudo: yes
#  tasks:
- name: "configure interface"
#  sudo: True
  lineinfile:
    dest: "/etc/network/interfaces"
    line: "{{ item }}"
  with_items:
    - "auto {{ contrail_vhost_device }}"
    - "iface {{ contrail_vhost_device }} inet static"
    - "\taddress {{ contrail_vhost_address }}"
    - "\tnetmask {{ contrail_vhost_netmask }}"

- name: "set interface address"
#  sudo: True
  shell: "ifconfig {{ contrail_vhost_device }} {{ contrail_vhost_address }} netmask {{ contrail_vhost_netmask }}"

- name: "up interface"
#  sudo: True
  shell: "ifconfig {{ contrail_vhost_device }} up"
