##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

packages:
  - python-cryptography
  - python-dateutil
  - python-dogpile.cache
  - python-eventlet
  - python-greenlet
  - python-jsonschema
  - python-keystoneclient
  - python-keystonemiddleware
  - python-ldap
  - python-ldappool
  - python-lxml
  - python-memcache
  - python-migrate
  - python-msgpack
  - python-mysqldb
  - python-oauthlib
  - python-openstackclient
  - python-oslo.cache
  - python-oslo.concurrency
  - python-oslo.config
  - python-oslo.context
  - python-oslo.db
  - python-oslo.i18n
  - python-oslo.log
  - python-oslo.messaging
  - python-oslo.middleware
  - python-oslo.policy
  - python-oslo.serialization
  - python-oslo.service
  - python-oslo.utils
  - python-pam
  - python-passlib
  - python-paste
  - python-pastedeploy
  - python-pbr
  - python-pycadf
  - python-pymysql
  - python-pysaml2
  - python-pysqlite2
  - python-routes
  - python-six
  - python-sqlalchemy
  - python-stevedore
  - python-webob
  - unzip
  - python3-keystoneauth1
  - python3-keystoneclient
  - python3-oslo.config
  - python3-oslo.context
  - python3-oslo.i18n
  - python3-oslo.serialization
  - python-oslo.service
  - python-oslo.utils
  - python-pam
  - python-passlib
  - python-paste
  - python-pastedeploy
  - python-pbr
  - python-pycadf
  - python-pymysql
  - python-pysaml2
  - python-pysqlite2
  - python-routes
  - python-six
  - python-sqlalchemy
  - python-stevedore
  - python-webob
  - unzip
  - python3-keystoneauth1
  - python3-keystoneclient
  - python3-oslo.config
  - python3-oslo.context
  - python3-oslo.i18n
  - python3-oslo.serialization
  - python3-oslo.utils
  - apache2
  - libapache2-mod-wsgi

services:
  - apache2

