---
- name: upload cinder conf
  template: src=cinder.conf dest=/etc/cinder/cinder.conf

- name: sync cinder db
  #cinder_manage: action=dbsync
  shell: cinder-manage db sync
  notify:
    - restart cinder control serveice
