---

sfc_plugins:
  src: sfc.conf
  dst: /opt/sfc.conf

# yamllint disable rule:line-length
tacker_horizon_repo: https://github.com/openstack/tacker-horizon.git
tacker_horizon_dir: /opt/tacker-horizon
tacker_horizon_branch: stable/ocata
openstack_release: 15.1.4
tacker_horizon_venv: "/openstack/venvs/horizon-{{ openstack_release }}"
tacker_horizon_enable_path: "{{ tacker_horizon_venv }}/lib/python2.7/site-packages/openstack_dashboard/enabled"
# yamllint enable rule:line-length
