##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: check if physical device exists
  stat: path={{ physical_device }}
  register: status
  tags:
    - storage

- name: load loop.yml
  include: loop.yml
  when: status.stat.exists == False or status.stat.isblk == False 
  tags:
    - storage

- name: load real.yml
  include: real.yml
  when: status.stat.exists == True and status.stat.isblk == True
  tags:
    - storage

- meta: flush_handlers
